# Strategy: Pre-build on Host (Native Speed), Package in Docker (x86 Compatibility)
# This avoids QEMU crashing during 'next build' on Mac Silicon

# Use slim Bullseye image (much smaller) since we don't compile in Docker anymore
FROM node:20-bullseye-slim

WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs


# 2. Copy Prisma Schema (Required for client generation)
COPY prisma ./prisma

# 3. Install Dependencies & Generate Prisma Client
# - npm ci: Install ALL deps (including 'prisma' CLI)
# - prisma generate: Generate client for Linux
# - npm prune: Remove devDeps (including 'prisma' CLI) to save space
COPY package.json package-lock.json* ./
RUN npm ci && npx prisma generate && npm prune --production && npm cache clean --force

# 2. Copy the Native Build Artifacts
# These are JS/CSS/HTML files generated by 'npm run build' on your Mac
# They are platform-independent
COPY .next-prod .next
COPY public public
COPY docs docs
# 2.1 Copy Chrome Extension (Required for version reading in API)
COPY chrome-extension chrome-extension

# 3. Permissions
RUN chown -R nextjs:nodejs /app/.next

USER nextjs

EXPOSE 3001

ENV PORT 3001
ENV HOSTNAME "0.0.0.0"

# Note: Standard build uses 'npm start', not 'node server.js'
CMD ["npm", "start"]
