# Strategy: Pre-build on Host (Native Speed), Package in Docker (x86 Compatibility)
# This avoids QEMU crashing during 'next build' on Mac Silicon

# Use full Bullseye image for maximum compatibility
FROM node:20-bullseye

WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# 1. Install Production Dependencies (x86)
# We do this INSIDE Docker to ensure we get Linux x64 binaries (not Mac ARM64)
COPY package.json package-lock.json* ./
RUN npm ci --only=production

# 2. Copy the Native Build Artifacts
# These are JS/CSS/HTML files generated by 'npm run build' on your Mac
# They are platform-independent
COPY .next .next
COPY public public

# 3. Permissions
RUN chown -R nextjs:nodejs /app/.next

USER nextjs

EXPOSE 3001

ENV PORT 3001
ENV HOSTNAME "0.0.0.0"

# Note: Standard build uses 'npm start', not 'node server.js'
CMD ["npm", "start"]
